apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- todo-backend-service.yaml
- todo-frontend-service.yaml
- todo-config-map.yaml
- todo-backend-deployment.yaml
- todo-frontend-deployment.yaml
- todo-secret.yaml